### ISSUE TITLE
Suggestion for additional Columns

### ISSUE THREAD

**Issue by ThomasBrodkorb** [martonsagi/al-object-designer#12]
I love this project and would like to contribute, but I'm unsure how to help, I could clone the project, but do not know how to compile, test and debug the modifications.

What I am aiming for:
Extend the objects ("newItem" in "ALObjectCollector", "_CheckObjectInProject" function) with "Extends ID" and "Extends Name" for the extension and customization objects, show them in object list

Allow to filter for "extended standard objects" (similar to Filter Modified = true in C/AL Object Designer).

Filters (in general) to filter for publisher.

See subscribers in events (show number of subscriptions with link to objects)

Add Object type "usercontrol"

**Comment by martonsagi** [comment]
Great ideas, thank you! I will create a wiki page on how to work with the project.

[TargetObject](https://github.com/martonsagi/al-object-designer/blob/master/extension-al-object-designer/src/ALObjectCollector.ts#L155) property contains the proposed "Extends Name" both for Symbols and local files. We can start from there with above changes.

**Comment by ThomasBrodkorb** [comment]
I added the code required and started a pull request.
I am not sure if I did everything right as this is my fiirst contribution in github. Can you please verify if you find the modifications I did?

**Comment by martonsagi** [comment]
It's been a while since you sent the pull requests and the current dev branch changed too much to merge in your changes.
However, I have extracted and implemented the functionality itself in the latest [0.0.7-alpha build](https://github.com/martonsagi/al-object-designer/blob/0.0.7-dev/custom-builds/al-object-designer-0.0.7-alpha.7.vsix). 

There is a new "Extends" column with the extended object name, which is a clickable link that navigates to the original object.
![image](https://user-images.githubusercontent.com/18100709/56855135-11dd8900-6942-11e9-9c0c-3b8629ccc248.png)
