### ISSUE TITLE
Usability request

### ISSUE THREAD

**Issue by Bleika** [martonsagi/al-object-designer#16]
Hi again :-)

I've been using your extension a lot today, and I've come to miss one thing: 

Many of us (at least the dinosaurs) still recall most Object IDs. Obviously you also manage the different Object Names in most cases, but it isn't always so. I.e.: I'm working on WMS right now and the names are impossible to know by memory (all the different abbreviations, hyphens, dots, etc.). In fact they're so messy that even IntelliSense gets lost... (you can try that on Codeunit 7324 "Whse.-Activity-Post"... yuck!!)

To solve this, I've been jumping to the old Developer Environment just to copy the Object Name.

On your object list, if you click on an Object Name it opens the Object definition.

**Do you think it would be possible to right-click just to copy the Object Name?**

**Comment by martonsagi** [comment]
Good idea. Sure, I think it is possible to utilize right-click event this way.

**Comment by martonsagi** [comment]
Hm, right-click events are disabled in VS Code WebViews, so that is not an option...

How about a new setting that would control how left clicking on Object Name should behave? 
E.g. a checkbox like "Copy Object Name to clipboard on mouse click instead of Symbol loading."

Not ideal but at least you could set different settings per workspace.

![image](https://user-images.githubusercontent.com/18100709/51734086-bd491a00-2083-11e9-93fc-31d75091575a.png)

**Comment by martonsagi** [comment]
I have been working on several updates, kept this one in mind as well.
I am using a new grid component that allows text selection/editing by double-clicking or hitting Enter on a table cell. This feature is activated for "Name" column. So double-clicking on the name cell, except the link, should show you the selected text that can be copied with ctrl+c.

This is available in [0.0.7-alpha build](https://github.com/martonsagi/al-object-designer/blob/0.0.7-dev/custom-builds/al-object-designer-0.0.7-alpha.7.vsix)

![al-table-designer_markedonly](https://user-images.githubusercontent.com/18100709/56855021-2882e080-6940-11e9-86a6-52dc87085947.PNG)
