### ISSUE TITLE
Error: 'Cannot read property 'extensionPath' of undefined'

### ISSUE THREAD

**Issue by stefanoPrimo** [martonsagi/al-object-designer#23]
AL Object Designer could not be opened. Error: 'Cannot read property 'extensionPath' of undefined'
This error shows up when I invoke the command "AL Object Designer"

Version: Al Object Designer 0.0.7-alpha.9

**Comment by martonsagi** [comment]
Hi,

This issue was related to a direct reference for `microsoft.al` AL Language extension. However, when downloaded from the Marketplace, the same extension has a different identifier.

It's fixed in the latest alpha build, you are welcome to test it. Thanks! :)

https://github.com/martonsagi/al-object-designer/blob/0.1.0-dev/custom-builds/al-object-designer-0.1.0-alpha.1.vsix
