### ISSUE TITLE
InternalEvent - "Discovering Objects" forever!

### ISSUE THREAD

**Issue by aptMattKoe** [martonsagi/al-object-designer#55]
**Problem:**
The "AL Object Designer" did not get any objects and stuck at "Discovering Objects"
![image](https://user-images.githubusercontent.com/57363453/77540086-c9588380-6ea2-11ea-8a28-56f3db85efa0.png)

**Reproduce:**
You coud reproduce it by adding an event with the **[InternalEvent](https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/methods/devenv-internal-attribute)** attribute:
![image](https://user-images.githubusercontent.com/57363453/77540255-09b80180-6ea3-11ea-8a47-ed2f2a0efcb0.png)

I think its a bug :/

**Comment by martonsagi** [comment]
Thanks for the feedback. InternalEvent type has beed added to the conditions, you can test it by installing [0.1.5-alpha1](https://github.com/martonsagi/al-object-designer/blob/master/custom-builds/al-object-designer-0.1.5-alpha1.vsix) build.

Since there could be million reasons why it gets stuck in "Discovering", I enhanced error display a bit. You should see an error notification in case it fails in another scenario.

**Comment by aptMattKoe** [comment]
Thanks @martonsagi, It works :)
And I hope not to see the better error display but I'm happy that there is one :D

**Comment by martonsagi** [comment]
Perfect, thanks! :)
